name: ClickUp Review Action

on:
  pull_request_review:
    types: [submitted, edited] 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: ClickUp Review
      if: contains(github.event.review.state, 'CHANGES_REQUESTED')
      uses: epona-science/actions@master
      with:
        clickup_secret: ${{ secrets.ClickUpSecret }}
        event_state: ${{ github.event.review.state }}
        head_ref: ${{ github.event.pull_request.head.ref }}
        status: "CHANGES REQUESTED"
